version: '3'

services:
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile.api
    container_name: librairie_api
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:5002"
    volumes:
      - ./api/:/usr/src/api/
    env_file:
      - ./.env.dev-sample
    ports:
      - "8002:5002"
    depends_on:
      - db

      


  public:
    build: 
      context: ./public
      dockerfile: Dockerfile.public
    container_name: librairie_public
    command: python manage.py runserver 0.0.0.0:5001
    volumes:
      - ./public/:/usr/src/public/
    env_file:
      - ./.env.dev-sample
    ports:
      - "8001:5001"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: librairie-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: librairie_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "8081:80"
    depends_on: 
      - "public"
      - "api"
      - "db"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/access.log:/var/log/nginx/access.log

volumes:
  postgres_data:
