# Generated by Django 5.1 on 2024-09-04 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categorie",
            fields=[
                ("id_categorie", models.AutoField(primary_key=True, serialize=False)),
                ("nom_categorie", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Etudiant",
            fields=[
                ("id_eleve", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=50)),
                ("prenom", models.CharField(max_length=50)),
                ("classe", models.CharField(max_length=50)),
                ("date_naissance", models.DateField()),
                ("adresse", models.CharField(max_length=255)),
                ("telephone", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Livre",
            fields=[
                ("id_livre", models.AutoField(primary_key=True, serialize=False)),
                ("titre", models.CharField(max_length=255)),
                ("auteur", models.CharField(max_length=255)),
                ("isbn", models.CharField(max_length=255)),
                ("genre", models.CharField(max_length=255)),
                ("date_publication", models.DateField()),
                ("nombre_exemplaires", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Personnel",
            fields=[
                ("id_personnel", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(max_length=255)),
                ("prenom", models.CharField(max_length=255)),
                ("poste", models.CharField(max_length=255)),
                ("date_embauche", models.CharField(max_length=255)),
                ("telephone", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Appartient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appli.categorie",
                    ),
                ),
                (
                    "id_livre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="appli.livre"
                    ),
                ),
            ],
            options={
                "unique_together": {("id_categorie", "id_livre")},
            },
        ),
        migrations.CreateModel(
            name="Emprunt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="appli.etudiant"
                    ),
                ),
                (
                    "id_livre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="appli.livre"
                    ),
                ),
                (
                    "id_personnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="appli.personnel",
                    ),
                ),
            ],
            options={
                "unique_together": {("id_eleve", "id_livre", "id_personnel")},
            },
        ),
    ]
