# Generated by Django 5.1 on 2024-09-12 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Auteur",
            fields=[
                ("id_auteur", models.AutoField(primary_key=True, serialize=False)),
                ("nom_auteur", models.CharField(max_length=255)),
                ("prenom_auteur", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="TypeLivre",
            fields=[
                ("id_type_livre", models.AutoField(primary_key=True, serialize=False)),
                ("nom_type", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="livre",
            name="auteur",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="livres",
                to="api.auteur",
            ),
        ),
        migrations.AddField(
            model_name="livre",
            name="type_livre",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="livres",
                to="api.typelivre",
            ),
        ),
    ]
