# Generated by Django 5.1 on 2024-09-12 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_auteur_typelivre_alter_livre_auteur_livre_type_livre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livre",
            name="auteur",
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name="livre",
            name="type_livre",
        ),
        migrations.DeleteModel(
            name="Auteur",
        ),
        migrations.DeleteModel(
            name="TypeLivre",
        ),
    ]
